### ISSUE TITLE
hot module replacement - possible to use some prior work

### ISSUE THREAD

**Issue by jeremy-coleman** [osdevisnot/sorvor#4]
Cool project, thank you for open sourcing it. I wanted to share something i thought could be useful for HMR stuff. See https://github.com/progrium/hotweb, its a bit more complicated but has a client lib too so maybe possible to incorporate prefresh or react-refresh. You can close this immediately after reading, just wanted to share and say thanks

**Comment by osdevisnot** [comment]
👋 @jeremy-coleman. Thank you for the pointers. This is really great project. My experience with HMR in past wasn't the greatest. But this project looks promising. I will dive into this once sorvor is little more stable.
